name: main

on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    paths-ignore:
    - .gitignore
    - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        msgpack: ['', '1']
        debug: ['', '1']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: install zmq
      run: |
        sudo apt-get update -qq && sudo apt-get install -qq libzmq3-dev
    - name: install python dependencies
      run: |
        pip install --upgrade pip setuptools wheel && \
        python setup.py install && \
        test ${{ matrix.msgpack }} == 1 && pip install msgpack; \
        pip install pyflakes pycodestyle docutils codecov black==22.8.0
    - name: test
      run: |
        python -c "import zmq; print('ZMQ version:', zmq.zmq_version())" && \
        pycodestyle --max-line-length=88 aiozmq examples tests benchmarks && \
        pyflakes . && \
        black --check aiozmq/ benchmarks/ examples/ tests/ setup.py runtests.py && \
        export USE_MSGPACK=${{ matrix.msgpack }} && \
        export PYTHONASYNCIODEBUG=${{ matrix.debug }} && \
        python setup.py check -rm  && \
        if python -c "import sys; sys.exit(sys.version_info < (3,5))"; then python setup.py check -s; fi && \
        python runtests.py --coverage -v
